### ISSUE TITLE
adjoint source on waveform plot scaled incorrectly

### ISSUE THREAD

**Issue by bch0w** [adjtomo/pyatoa#18]
This is a recurring issue but the adjoint source, which is plotted on a twin axis in the wave_maker, occasionally gets scaled completely incorrectly, leading to figures with really blown out adjoint sources (see attached).

Looks like this is happening because the twin X axis is not being set correctly, so it is being scaled from 0 to 1 when it needs to be going something like +/- 1e5 or more. 

![XV F1TN](https://user-images.githubusercontent.com/23055374/196821350-dd78f964-38fd-45f5-a6eb-b0493fa32d50.png)

**Comment by aakash10gupta** [comment]
Adding to the thread screenshots of plotting errors I've witnessed in my inversions -

seismogram plotting error -
<img width="1113" alt="seismogram_plotting_error" src="https://github.com/user-attachments/assets/93b3dd88-2eb8-4e2b-adde-f43ea819c23a">

adjoint source plotting error -
<img width="1113" alt="adjoint_source_plotting_error" src="https://github.com/user-attachments/assets/9e1260c3-37bc-4616-8445-1ad2dfa6807a">

**Comment by bch0w** [comment]
> Not sure if this is the best thread to discuss, but I'm noticing that while the images you posted have an `OBS` and `SYN` in the legend, mine only has `OBS` and `OBS`.

Thanks for the reminder, that is fixed here: https://github.com/adjtomo/pyatoa/pull/48/commits/5765d71402afc0f087af7fdc0392457fa55027d9

**Comment by aakash10gupta** [comment]
Also, when I used `unit_output: VEL` for my earlier inversion tests, the generated plots still had units for displacements on the y-axis. Possibly the error persists even when `unit_output: ACC` is used.

I'm also not sure if the printed units for the adjoint sources is correct for each of the `unit_output` cases, as well as for the different `adj_src_type` options.

**Comment by bch0w** [comment]
> Also, when I used `unit_output: VEL` for my earlier inversion tests, the generated plots still had units for displacements on the y-axis. Possibly the error persists even when `unit_output: ACC` is used.
> 
> I'm also not sure if the printed units for the adjoint sources is correct for each of the `unit_output` cases, as well as for the different `adj_src_type` options.

Thanks for pointing that out, that is a seisflows issue, I will fix in PR #230 or in another PR

**Comment by bch0w** [comment]
Closed with #48
